### ISSUE TITLE
Enhancement - Add Docs about refinements

### ISSUE THREAD

**Issue by octosteve** [learn-co-curriculum/oo-counting-sentences#1]
Ruby 2.1 has a feature called [Refinements ](http://ruby-doc.org/core-2.1.1/doc/syntax/refinements_rdoc.html) that allows for local monkey patches. I usually mention it them when I do this review. I do it the way the solution suggests, then I talk about the Evils of Duck Punching, and offer refinements as a solution.

Here's another article on refinements. http://timelessrepo.com/refinements-in-ruby

Thoughts? @aviflombaum 

I'm suggesting we add some documentation on Refinements in this lab. This is part of a larger question: "Do we always teach the latest and greatest Ruby has to offer?"

**Comment by AnnJohn** [comment]
Iceboxing the issue for now

**Comment by aviflombaum** [comment]
No, we're not putting refinements here. For one, refinements are getting re-implemented in ruby. And if we want to teach refinements, we'll put that in an entirely different lab. Thanks though! <3

**Comment by octosteve** [comment]
@aviflombaum Where did you read about refinements being re-implemented? I can't imagine a backend change would change the API. Either way, I'm good.
