### ISSUE TITLE
missing exclamation mark

### ISSUE THREAD

**Issue by gooryalhamed** [learn-co-curriculum/oo-counting-sentences#16]
Hello! Inside spec/count_sentences.rb there is the following:
 it  "returns the number of sentences in a string" do
      expect("one. two. three?".count_sentences).to eq(3)
    end
the test will not raise an error if the coder forget to include exclamation mark within their code.
And according to the lesson, the exclamation mark can split the string.

**Comment by curiositypaths** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
