### ISSUE TITLE
Solutions discrepancy

### ISSUE THREAD

**Issue by abonner1** [learn-co-curriculum/oo-counting-sentences#17]
I suppose this is more of a suggestion than an issue.

The readme prompts the student to use #split and #count in order to discover how many sentences there are in the string, but the solution strings the #split method (with a regular expression as the argument) and the #delete_if method in order to solve the test.

Though it is a useful thing to know, it doesn't show the student how to call the #split and #count methods in the context of this particular lesson.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. From time to time the prepared solution might diverge from the solution approach suggested in the readme. 

If you still feel that this is an issue with the curriculum itself, please feel free to reopen the issue.

As always, thanks for contributing! 💙
