### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/oo-counting-sentences#8]
Let's rename this: oo-self-sentences

This lab is explicitly about using `self` within the context of instance methods.

We want to make the user build the following methods on `String` that will force them to refer to the instance of the string as `self`.

`#sentence?` must end in a period 
`#question?`  must end in a question mark
`#exclamation?` must end in an exclamation mark.

`#count_full_sentences` returns the count of full sentences of the three types.

**Comment by AnnJohn** [comment]
Fixed
